### ISSUE TITLE
Silent option should not show host timeout

### ISSUE THREAD

**Issue by sieunhando** [nccgroup/dirble#39]
Hi, I think the silent option(-S) should not show host timeout (Timeout was reached) in runtime. You can make it show at the final result. 
And in silent, that will be nice if you can put a processing bar into it :D

**Comment by Isona** [comment]
Hi, I've only just got around to responding to this issue, sorry. I think it's important to show errors as they happen, even in silent mode, otherwise it would be very hard to know if your scan is working. I also don't think that errors should be shown in the final report due to them being largely clutter.
A processing bar would be extremely hard to make due to the nature of the threading, but I would like to add something like nmap's status, where it tells you the current progress when you press a key. An example would be something like "Current threads running: 10, Threads in queue: 25, Threads completed: 5, Time taken: 5 minutes 30 seconds" (this is definitely not a final look, but this is some of the information that might be included).
